name: Blender daily build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - main
      - 'run-ci/**'
  pull_request:

jobs:
  build_blender:
    name: Build Blender
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Blender sources from GitHub
        uses: actions/checkout@v2
        with:
          repository: "blender/blender"
          path: blender-build/blender
      - name: Install dependencies
        run: |
          ./blender-build/blender/build_files/build_environment/windows/buildall.cmd
          sudo apt install -y libglfw3 libgles2-mesa-dev
      - name: Checkout Blender libraries
        run: |
          mkdir blender-build/lib
          cd blender-build/lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc15
      - name: Build Blender
        run: |
          cd blender-build/blender
          make update
          make
      - name: Compress Blender for the artifacts
        run: |
          mkdir release
          cp -r blender-build/build_windows/bin release/blender
          cd release
          tar Jcf blender.tar.xz blender
          rm -rf blender
      - name: Create MD5 checksum file
        run: |
          cd release
          md5sum blender.tar.xz > blender.tar.xz.md5
      - name: Upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: blender
          path: "release"
